### ISSUE TITLE
Make Bork work more consistently across differently environments

### ISSUE THREAD

**Issue by duckinator** [duckinator/bork#185]
I am incredibly tired of having to throw this in `.cirrus.yml` for projects using Bork:

```
# This makes Click, a Bork dependency, behave itself.
env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8
```

I'm unsure whether I want to switch away from Click, or if it's better to just add a kludge of some sort.
