### ISSUE TITLE
Switch away from Click for CLI parsing

### ISSUE THREAD

**Issue by duckinator** [duckinator/bork#205]
Click seems to just... try too hard? It's repeatedly caused problems, and honestly I'd rather just rip it out and use something else.

**Comment by nbraud** [comment]
Which alternatives are you considering?

FWIW, I like that we can generate decent manpages from the Click CLI code, but that can probably be done with whatever other tool for building CLIs declaratively.

**Comment by duckinator** [comment]
I'm not sure what I want to use instead, and am open to suggestions. The main problem is needing _everyone_ who uses bork needing to set up their environment purely to satisfy an arbitrary restriction placed by Click &mdash; like this snippet from Emanate's `.cirrus.yml`:

```
# http://click.palletsprojects.com/en/5.x/python3/#python-3-surrogate-handling
env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8
```
