### ISSUE TITLE
Bork zipapp breaks resolver?

### ISSUE THREAD

**Issue by AstraLuma** [duckinator/bork#350]
```toml
[project]
name = "unholy"

[tool.poetry]
name = "unholy"
version = "0.1.0"
description = "The melding of docker compose and neovim"
authors = ["Jamie Bliss <jamie@ivyleav.es>"]
license = "GPL-3"
readme = "README.md"
repository = "https://github.com/AstraLuma/unholy"

[tool.poetry.dependencies]
python = ">3.10"
click = "^8.1.3"
docker = "^6.0.1"
tomlkit = "^0.12.2"
appdirs = "^1.4.4"

[tool.poetry.scripts]
unholy = 'unholy:main'

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"

[tool.bork.zipapp]
enabled = true
main = "unholy:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

```console
astraluma@nandi ~/code/unholy trunk [1] @ bork build
Processing ./dist/unholy-0.1.0-py3-none-any.whl
Collecting appdirs<2.0.0,>=1.4.4 (from unholy==0.1.0)
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting click<9.0.0,>=8.1.3 (from unholy==0.1.0)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting docker<7.0.0,>=6.0.1 (from unholy==0.1.0)
  Downloading docker-6.1.3-py3-none-any.whl.metadata (3.5 kB)
Collecting tomlkit<0.13.0,>=0.12.2 (from unholy==0.1.0)
  Using cached tomlkit-0.12.3-py3-none-any.whl.metadata (2.7 kB)
Collecting packaging>=14.0 (from docker<7.0.0,>=6.0.1->unholy==0.1.0)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting requests>=2.26.0 (from docker<7.0.0,>=6.0.1->unholy==0.1.0)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting urllib3>=1.26.0 (from docker<7.0.0,>=6.0.1->unholy==0.1.0)
  Using cached urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Collecting websocket-client>=0.32.0 (from docker<7.0.0,>=6.0.1->unholy==0.1.0)
  Downloading websocket_client-1.6.4-py3-none-any.whl.metadata (7.7 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.26.0->docker<7.0.0,>=6.0.1->unholy==0.1.0)
  Using cached charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests>=2.26.0->docker<7.0.0,>=6.0.1->unholy==0.1.0)
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting certifi>=2017.4.17 (from requests>=2.26.0->docker<7.0.0,>=6.0.1->unholy==0.1.0)
  Using cached certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Downloading docker-6.1.3-py3-none-any.whl (148 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.1/148.1 kB 9.2 MB/s eta 0:00:00
Using cached tomlkit-0.12.3-py3-none-any.whl (37 kB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Downloading websocket_client-1.6.4-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 21.0 MB/s eta 0:00:00
Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Using cached charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Installing collected packages: appdirs, websocket-client, urllib3, tomlkit, packaging, idna, click, charset-normalizer, certifi, requests, docker, unholy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bork 7.0.2 requires packaging~=21.3, but you have packaging 23.2 which is incompatible.
Successfully installed appdirs-1.4.4 certifi-2023.11.17 charset-normalizer-3.3.2 click-8.1.7 docker-6.1.3 idna-3.6 packaging-23.2 requests-2.31.0 tomlkit-0.12.3 unholy-0.1.0 urllib3-2.1.0 websocket-client-1.6.4
```

I'm honestly not sure why bork is being installed?
