### ISSUE TITLE
setuptools + setuptools_scm + bork = v0.0.0

### ISSUE THREAD

**Issue by AstraLuma** [duckinator/bork#352]
https://cirrus-ci.com/task/6058258926927872

I'm able to reproduce this locally with `bork build`, but `python -m build` works.

**Comment by AstraLuma** [comment]
https://github.com/ppb/pursuedpybear/blob/18351e0aa9a4e33cb69c4b3c77ff024287afa6d0/.cirrus.yml#L16-L24

```yaml
build_task:
  container:
    image: duckinator/bork
  setup_script:
    - git fetch --tags
  script:
    - bork build
  dist_artifacts:
    path: "dist/**"
```
